name: EC2 Deployment and Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script on Ec2 Server
      uses: appleboy/ssh-action@master
      with:
        host: ec2-43-201-140-54.ap-northeast-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.AWS_PEM_KEY }}
        script: |
          /home/ubuntu/runserve.sh
          # Insert your script here
      if: github.ref == 'refs/heads/main'


  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: setting java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
  
    - name: Execute Gradle build
      run: |
        cd Backend
        echo "${{ secrets.APP_YML }}" > src/main/resources/application.yml
        ./gradlew test
      if: github.ref == 'refs/heads/dev'
  
  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name : Setup npm
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name : Run npm build Test
      run: |
        cd Frontend/fe_vue
        npm install
        npm run build
      if: github.ref == 'refs/heads/dev'

