name: EC2 Deployment and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script on Ec2 Server
      uses: appleboy/ssh-action@master
      with:
        host: ec2-43-201-140-54.ap-northeast-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.AWS_PEM_KEY }}
        script: |
          /home/ubuntu/runserve.sh
          # Insert your script here

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to Backend folder
      run: cd Backend
    
    - name: check the Structure of Folder
      run: tree

    - name: Use Gradle 7.1.1
      run: gradle wrapper --gradle-version 7.1.1

    - name: Gradle Test
      run: ./gradlew test
      if: github.ref == 'refs/heads/dev'
