name: EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script on My CustomServer
      uses: appleboy/ssh-action@master
      with:
        host: ec2-43-201-140-54.ap-northeast-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.AWS_PEM_KEY }}
        script: |
          /home/ubuntu/runserve.sh
          # Insert your script here
